//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLibs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public int IdCidade { get; set; }
        public int IdEstado { get; set; }
        public string nome { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
